<a href="https://colab.research.google.com/github/ZuoTianyu/Assignment/blob/master/Pytorch/Pytorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Tutorial**


In [3]:
import torch

**1. Pytorch Documentation Explanation with torch.max**



In [4]:
x = torch.randn(4,5)
y = torch.randn(4,5)
z = torch.randn(4,5)
print(x)
print(y)
print(z)

tensor([[ 0.3297, -1.4686,  0.0221,  0.1954, -1.3906],
        [ 0.5979, -1.5440, -0.1009, -0.1101, -0.8318],
        [-0.1363,  0.2551,  0.5056, -0.0735,  0.2612],
        [ 0.1630, -0.6568,  1.4421,  1.6800, -1.0757]])
tensor([[-1.1586,  1.1279, -1.3636,  0.9300,  0.9737],
        [-0.0225, -1.9297, -1.0621, -1.3848,  0.1265],
        [-0.4253, -1.1343, -0.0105,  0.4627, -0.8802],
        [ 0.5649, -1.7655, -1.5282, -0.0105,  0.0393]])
tensor([[ 2.3200,  0.1901, -0.5940, -0.9345, -2.1305],
        [ 2.6991,  0.5636, -0.4128, -0.1431,  1.2940],
        [-0.5088,  0.7324,  0.8903, -0.2858, -0.6783],
        [-0.4984, -2.8363, -1.0800,  0.5054, -3.3575]])


In [5]:
# 1. max of entire tensor (torch.max(input) → Tensor)
m = torch.max(x)
print(m)

tensor(1.6800)


In [6]:
# 2. max along a dimension (torch.max(input, dim, keepdim=False, *, out=None) → (Tensor, LongTensor))
m, idx = torch.max(x,0)
print(m)
print(idx)

tensor([0.5979, 0.2551, 1.4421, 1.6800, 0.2612])
tensor([1, 2, 3, 3, 2])


In [7]:
# 2-2
m, idx = torch.max(input=x,dim=0)
print(m)
print(idx)

tensor([0.5979, 0.2551, 1.4421, 1.6800, 0.2612])
tensor([1, 2, 3, 3, 2])


In [8]:
# 2-3
m, idx = torch.max(x,0,False)
print(m)
print(idx)

tensor([0.5979, 0.2551, 1.4421, 1.6800, 0.2612])
tensor([1, 2, 3, 3, 2])


In [9]:
# 2-4
m, idx = torch.max(x,dim=0,keepdim=True)
print(m)
print(idx)

tensor([[0.5979, 0.2551, 1.4421, 1.6800, 0.2612]])
tensor([[1, 2, 3, 3, 2]])


In [15]:
# 2-5
p = (m,idx)
torch.max(x,0,False,out=p)
print(p[0])
print(p[1])


tensor([0.5979, 0.2551, 1.4421, 1.6800, 0.2612])
tensor([1, 2, 3, 3, 2])


In [17]:
# 2-6
p = (m,idx)
torch.max(x,0,False,out=p)
print(p[0])
print(p[1])

tensor([0.5979, 0.2551, 1.4421, 1.6800, 0.2612])
tensor([1, 2, 3, 3, 2])


In [21]:
# 2-7
m, idx = torch.max(x,0,True)

In [22]:
# 3. max(choose max) operators on two tensors (torch.max(input, other, *, out=None) → Tensor)
t = torch.max(x,y)
print(t)

tensor([[ 0.3297,  1.1279,  0.0221,  0.9300,  0.9737],
        [ 0.5979, -1.5440, -0.1009, -0.1101,  0.1265],
        [-0.1363,  0.2551,  0.5056,  0.4627,  0.2612],
        [ 0.5649, -0.6568,  1.4421,  1.6800,  0.0393]])


**2. Common errors**



The following code blocks show some common errors while using the torch library. First, execute the code with error, and then execute the next code block to fix the error. You need to change the runtime to GPU.


In [23]:
import torch

In [24]:
# 1. different device error
model = torch.nn.Linear(5,1).to("cuda:0")
x = torch.Tensor([1,2,3,4,5]).to("cpu")
y = model(x)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)

In [25]:
# 1. different device error (fixed)
x = torch.Tensor([1,2,3,4,5]).to("cuda:0")
y = model(x)
print(y.shape)

torch.Size([1])


In [26]:
# 2. mismatched dimensions error
x = torch.randn(4,5)
y= torch.randn(5,4)
z = x + y

RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1

In [27]:
# 2. mismatched dimensions error (fixed)
y= y.transpose(0,1)
z = x + y
print(z.shape)

torch.Size([4, 5])


In [30]:
# 3. cuda out of memory error
# 当将 2048 张图像的数据 (data) 一次性加载到 GPU 上时，这些数据占用的显存超过了 GPU 的容量，导致 CUDA Out of Memory 错误。
import torch
import torchvision.models as models
resnet18 = models.resnet18().to("cuda:0") # Neural Networks for Image Recognition
data = torch.randn(2048,3,244,244) # Create fake data (512 images)
out = resnet18(data.to("cuda:0")) # Use Data as Input and Feed to Model
print(out.shape)


OutOfMemoryError: CUDA out of memory. Tried to allocate 7.27 GiB. GPU 0 has a total capacity of 14.75 GiB of which 4.46 GiB is free. Process 3089 has 10.29 GiB memory in use. Of the allocated memory 10.12 GiB is allocated by PyTorch, and 47.71 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

In [31]:
# 3. cuda out of memory error (fixed)
# 使用循环逐张图片处理，而不是一次性将所有 2048 张图片加载到 GPU。
for d in data:
  out = resnet18(d.to("cuda:0").unsqueeze(0)) # 在批次维度上为单张图片增加一个维度，因为模型需要输入形状为 (batch_size, channels, height, width)。
print(out.shape)                              # e.g. d 的形状是 (3, 244, 244)，加了 .unsqueeze(0) 后变成 (1, 3, 244, 244)。

torch.Size([1, 1000])


In [34]:
# 4. mismatched tensor type
import torch.nn as nn
# nn.CrossEntropyLoss 要求 labels 必须是整数类型 (LongTensor)，而不是浮点类型 (FloatTensor)。
L = nn.CrossEntropyLoss()
outs = torch.randn(5,5)
# 定义标签，包含 5 个样本的类别索引
labels = torch.Tensor([1,2,3,4,0])    # 注意 labels 是 torch.Tensor 类型 (默认是 float32)
lossval = L(outs,labels)           # Calculate CrossEntropyLoss between outs and labels

RuntimeError: expected scalar type Long but found Float

In [36]:
# 4. mismatched tensor type (fixed)
labels = labels.long()
lossval = L(outs,labels)
print(lossval)

tensor(2.6261)


**3. More on dataset and dataloader**


A dataset is a cluster of data in a organized way. A dataloader is a loader which can iterate through the data set.

Let a dataset be the English alphabets "abcdefghijklmnopqrstuvwxyz"

In [37]:
dataset = "abcdefghijklmnopqrstuvwxyz"

A simple dataloader could be implemented with the python code "for"

In [38]:
for datapoint in dataset:
  print(datapoint)

a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z


When using the dataloader, we often like to shuffle the data. This is where torch.utils.data.DataLoader comes in handy. If each data is an index (0,1,2...) from the view of torch.utils.data.DataLoader, shuffling can simply be done by shuffling an index array.



torch.utils.data.DataLoader will need two imformation to fulfill its role. First, it needs to know the length of the data. Second, once torch.utils.data.DataLoader outputs the index of the shuffling results, the dataset needs to return the corresponding data.

Therefore, torch.utils.data.Dataset provides the imformation by two functions, `__len__()` and `__getitem__()` to support torch.utils.data.Dataloader

In [39]:
import torch
import torch.utils.data
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"

  def __getitem__(self,idx): # if the index is idx, what will be the data?
    return self.data[idx]

  def __len__(self): # What is the length of the dataset
    return len(self.data)

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)

['a']
['i']
['n']
['q']
['g']
['r']
['h']
['j']
['d']
['l']
['z']
['y']
['p']
['x']
['w']
['s']
['f']
['o']
['v']
['k']
['u']
['e']
['b']
['c']
['m']
['t']


A simple data augmentation technique can be done by changing the code in `__len__()` and `__getitem__()`. Suppose we want to double the length of the dataset by adding in the uppercase letters, using only the lowercase dataset, you can change the dataset to the following.

In [40]:
import torch.utils.data
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"

  def __getitem__(self,idx): # if the index is idx, what will be the data?
    if idx >= len(self.data): # if the index >= 26, return upper case letter
      return self.data[idx%26].upper()
    else: # if the index < 26, return lower case, return lower case letter
      return self.data[idx]

  def __len__(self): # What is the length of the dataset
    return 2 * len(self.data) # The length is now twice as large

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)

['v']
['c']
['y']
['J']
['M']
['V']
['W']
['I']
['x']
['N']
['a']
['r']
['A']
['z']
['n']
['e']
['U']
['l']
['w']
['b']
['X']
['Y']
['H']
['h']
['F']
['s']
['G']
['S']
['K']
['j']
['Q']
['k']
['O']
['g']
['o']
['P']
['d']
['t']
['E']
['C']
['f']
['L']
['T']
['p']
['q']
['R']
['Z']
['u']
['D']
['i']
['B']
['m']
